version: '3.9'

services:
    app:
        depends_on:
            db:
                condition: service_healthy
                restart: true
        container_name: test-app
        working_dir: /app
        build: .
        ports:
            - '5555:5555'
        env_file: ./.env
        volumes:
            - ./src:/app/src
        restart: unless-stopped
        stdin_open: true
        tty: true
        networks:
            - test-network

    db:
        image: postgres
        container_name: pg-5435
        restart: unless-stopped
        env_file: ./.env
        environment:
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: admin
            POSTGRES_DB: test
        ports:
            - '5435:5432'
        volumes:
            - db:/var/lib/postgresql/data
        networks:
            - test-network
        healthcheck:
            test:
                [
                    'CMD-SHELL',
                    'pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}',
                ]
            interval: 10s
            timeout: 5s
            retries: 5

volumes:
    db:

networks:
    test-network:
        driver: bridge
        name: test-network
